language: python
matrix:
  allow_failures:
    - os: osx
    - os: windows
  include:
    - name: "Python on Linux"
      dist: xenial
      python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8-dev"
        - "nightly"
        - "pypy3.5"
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2
      language: shell
cache:
  directories:
    - $HOME/.cache/pip
    - .pytest_cache
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
script:
  - pytest -v
before_deploy:
  - python3 setup.py bdist_wheel || python setup.py bdist_wheel
deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
      branch: master
  - provider: releases
    api_key:
      secure: oWIFX7Y7lqXRcp0A9hTuhBhoQFnaYG2Iqhwm6pOpnqi6glaA5oOphdUR9MP1VX/4zKLvX+ZNIz+bIg3D1ou+WjvVCt2LJQi9+6KINSEX2EP/fFE68EcvfRT3RImrcsXcmYCeIGW4GfxMgzdR3IoJzefhvWwAB0UIfDboRg1vJAIbxzIZy3SXaft9HbKxJD1Wyc5DKUv/mNeJ78FAsnePPnbt7z8jq9jMgB3e8jmc5kfbMnvzW/eYNkslCXtu7RwuEswFwDr3UMbC1KXKEtuLw4DF+5xOA/7IgzCxtHeJ5kX95Id9dqrPSSqEljq81rJD+dTM1r0m7faDgp39Zzw59KIkM2gDBIOk+0kJXi8Qrel+Ni/6XBglA9NrfRVyrminVh2Q+De4OFXnrD4rIneCEsPDwqGGNW0X/w+1FRzkicJHrRZZAddMmxs7jP9izdeMbWRKshuXN2i/sad/78etQBMyvfvn+GyvxQOiKk/GSP7Yl5dWb0S55JsK4yNQFP4f/aAZhASAPDyqRj3TTUJWLgFetJSw3jRmBfA3GnK6yngRBOhyh+5henaSqTCJaVO4py2vRBJuoVHDPYJ9aOp7DKVG4sa5H5k6w9m7fPM9lhkg1BbIFEYQqxktIc15GmCNCiEFK5rlZSa6Yh74mryCQjtOyfPgYnfbmVycoI5ZZqk=
    file_glob: true
    file: "dist/*.whl"
    skip_cleanup: true
    on:
      tags: true
      branch: master
